### ISSUE TITLE
Duplicate / Redundant facts

### ISSUE THREAD

**Issue by Caelink** [Caelink/lucashifacts#31]
Our factlist is clearly being maintained by monkeys with typewriters. Lines 4 and 85 as well as lines 17 and 25 seem to be redundant. Is this a feature, or a bug? Do we need to resource better checking on these PRs? I can talk to management if we need to push back on rushing out products that aren't fully ready. @karlding @Hazematman @tituschow

**Comment by karlding** [comment]
Fixed in #49
