### ISSUE TITLE
Fix shellcheck errors in JSON parser so we can use it

### ISSUE THREAD

**Issue by Caelink** [Caelink/lucashifacts#48]
See the newly proposed json.sh in https://github.com/Caelink/lucashifacts/pull/47

**Comment by karlding** [comment]
Let me know if you don't have enough cycles to handle this, and maybe I can take this on.

**Comment by Caelink** [comment]
https://github.com/dominictarr/JSON.sh/blob/master/JSON.sh is the source, credit to karlding. I don't think I've got the bandwidth for this right now so feel free to take it on, but if you need to sync up lmk.

**Comment by karlding** [comment]
Are we okay with disabling SC2039 for the file to give us properly locally scoped variables? This [StackOverflow article](https://stackoverflow.com/questions/18597697/posix-compliant-way-to-scope-variables-to-a-function-in-a-shell-script#answer-18600920) seems to suggest that this is fine. See [this build](https://travis-ci.org/Caelink/lucashifacts/builds/274930688?utm_source=github_status&utm_medium=notification) for context.

The alternative would probably be to not locally scope anything (like what we're currently doing) and just pray that nobody else tries to use the same variables.

Edit: I suspect we won't need the portability, so I've set our shebang to `#!/bin/bash`, which should fix this issue.

**Comment by karlding** [comment]
Fixed in #50
